databases:
  - name: salish-distro-backend
    databaseName: salish-distro-backend
    user: salish-distro-backend

services:
  - type: web
    name: salish-distro-backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: salish-distro-backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false